//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfrva.Sti.Sms.CDCServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", ConfigurationName="CDCServices.NPINDataWebservicesSoap")]
    public interface NPINDataWebservicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetHIVDataBy" +
            "Index", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexResponse GetHIVDataByIndex(Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetHIVDataBy" +
            "Index", ReplyAction="*")]
        System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexResponse> GetHIVDataByIndexAsync(Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetHIVDataBy" +
            "State", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateResponse GetHIVDataByState(Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetHIVDataBy" +
            "State", ReplyAction="*")]
        System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateResponse> GetHIVDataByStateAsync(Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetSTDDataBy" +
            "Index", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexResponse GetSTDDataByIndex(Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetSTDDataBy" +
            "Index", ReplyAction="*")]
        System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexResponse> GetSTDDataByIndexAsync(Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetWidgetDat" +
            "a", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cfrva.Sti.Sms.CDCServices.GetWidgetDataResponse GetWidgetData(Cfrva.Sti.Sms.CDCServices.GetWidgetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetWidgetDat" +
            "a", ReplyAction="*")]
        System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetWidgetDataResponse> GetWidgetDataAsync(Cfrva.Sti.Sms.CDCServices.GetWidgetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetSTDWidget" +
            "Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataResponse GetSTDWidgetData(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetSTDWidget" +
            "Data", ReplyAction="*")]
        System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataResponse> GetSTDWidgetDataAsync(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetSTDWidget" +
            "DataWithAudience", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceResponse GetSTDWidgetDataWithAudience(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetSTDWidget" +
            "DataWithAudience", ReplyAction="*")]
        System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceResponse> GetSTDWidgetDataWithAudienceAsync(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetWidgetDat" +
            "aWithAudience", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceResponse GetWidgetDataWithAudience(Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML/GetWidgetDat" +
            "aWithAudience", ReplyAction="*")]
        System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceResponse> GetWidgetDataWithAudienceAsync(Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHIVDataByIndex", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetHIVDataByIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=1)]
        public string radius;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=2)]
        public string index;
        
        public GetHIVDataByIndexRequest() {
        }
        
        public GetHIVDataByIndexRequest(string zip, string radius, string index) {
            this.zip = zip;
            this.radius = radius;
            this.index = index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHIVDataByIndexResponse", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetHIVDataByIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public System.Xml.XmlNode GetHIVDataByIndexResult;
        
        public GetHIVDataByIndexResponse() {
        }
        
        public GetHIVDataByIndexResponse(System.Xml.XmlNode GetHIVDataByIndexResult) {
            this.GetHIVDataByIndexResult = GetHIVDataByIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHIVDataByState", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetHIVDataByStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public string state;
        
        public GetHIVDataByStateRequest() {
        }
        
        public GetHIVDataByStateRequest(string state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHIVDataByStateResponse", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetHIVDataByStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public System.Xml.XmlNode GetHIVDataByStateResult;
        
        public GetHIVDataByStateResponse() {
        }
        
        public GetHIVDataByStateResponse(System.Xml.XmlNode GetHIVDataByStateResult) {
            this.GetHIVDataByStateResult = GetHIVDataByStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSTDDataByIndex", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetSTDDataByIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=1)]
        public string radius;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=2)]
        public string index;
        
        public GetSTDDataByIndexRequest() {
        }
        
        public GetSTDDataByIndexRequest(string zip, string radius, string index) {
            this.zip = zip;
            this.radius = radius;
            this.index = index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSTDDataByIndexResponse", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetSTDDataByIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public System.Xml.XmlNode GetSTDDataByIndexResult;
        
        public GetSTDDataByIndexResponse() {
        }
        
        public GetSTDDataByIndexResponse(System.Xml.XmlNode GetSTDDataByIndexResult) {
            this.GetSTDDataByIndexResult = GetSTDDataByIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWidgetData", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetWidgetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=1)]
        public string radius;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=2)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=3)]
        public string widgetcode;
        
        public GetWidgetDataRequest() {
        }
        
        public GetWidgetDataRequest(string zip, string radius, string url, string widgetcode) {
            this.zip = zip;
            this.radius = radius;
            this.url = url;
            this.widgetcode = widgetcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWidgetDataResponse", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetWidgetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public System.Xml.XmlNode GetWidgetDataResult;
        
        public GetWidgetDataResponse() {
        }
        
        public GetWidgetDataResponse(System.Xml.XmlNode GetWidgetDataResult) {
            this.GetWidgetDataResult = GetWidgetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSTDWidgetData", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetSTDWidgetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=1)]
        public string radius;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=2)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=3)]
        public string widgetcode;
        
        public GetSTDWidgetDataRequest() {
        }
        
        public GetSTDWidgetDataRequest(string zip, string radius, string url, string widgetcode) {
            this.zip = zip;
            this.radius = radius;
            this.url = url;
            this.widgetcode = widgetcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSTDWidgetDataResponse", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetSTDWidgetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public System.Xml.XmlNode GetSTDWidgetDataResult;
        
        public GetSTDWidgetDataResponse() {
        }
        
        public GetSTDWidgetDataResponse(System.Xml.XmlNode GetSTDWidgetDataResult) {
            this.GetSTDWidgetDataResult = GetSTDWidgetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSTDWidgetDataWithAudience", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetSTDWidgetDataWithAudienceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=1)]
        public string radius;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=2)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=3)]
        public string widgetcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=4)]
        public string audience;
        
        public GetSTDWidgetDataWithAudienceRequest() {
        }
        
        public GetSTDWidgetDataWithAudienceRequest(string zip, string radius, string url, string widgetcode, string audience) {
            this.zip = zip;
            this.radius = radius;
            this.url = url;
            this.widgetcode = widgetcode;
            this.audience = audience;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSTDWidgetDataWithAudienceResponse", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetSTDWidgetDataWithAudienceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public System.Xml.XmlNode GetSTDWidgetDataWithAudienceResult;
        
        public GetSTDWidgetDataWithAudienceResponse() {
        }
        
        public GetSTDWidgetDataWithAudienceResponse(System.Xml.XmlNode GetSTDWidgetDataWithAudienceResult) {
            this.GetSTDWidgetDataWithAudienceResult = GetSTDWidgetDataWithAudienceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWidgetDataWithAudience", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetWidgetDataWithAudienceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=1)]
        public string radius;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=2)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=3)]
        public string widgetcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=4)]
        public string audience;
        
        public GetWidgetDataWithAudienceRequest() {
        }
        
        public GetWidgetDataWithAudienceRequest(string zip, string radius, string url, string widgetcode, string audience) {
            this.zip = zip;
            this.radius = radius;
            this.url = url;
            this.widgetcode = widgetcode;
            this.audience = audience;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWidgetDataWithAudienceResponse", WrapperNamespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", IsWrapped=true)]
    public partial class GetWidgetDataWithAudienceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cdcnping.org/NPINWebservicesXML/NPINDataWebServicesRawXML", Order=0)]
        public System.Xml.XmlNode GetWidgetDataWithAudienceResult;
        
        public GetWidgetDataWithAudienceResponse() {
        }
        
        public GetWidgetDataWithAudienceResponse(System.Xml.XmlNode GetWidgetDataWithAudienceResult) {
            this.GetWidgetDataWithAudienceResult = GetWidgetDataWithAudienceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NPINDataWebservicesSoapChannel : Cfrva.Sti.Sms.CDCServices.NPINDataWebservicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NPINDataWebservicesSoapClient : System.ServiceModel.ClientBase<Cfrva.Sti.Sms.CDCServices.NPINDataWebservicesSoap>, Cfrva.Sti.Sms.CDCServices.NPINDataWebservicesSoap {
        
        public NPINDataWebservicesSoapClient() {
        }
        
        public NPINDataWebservicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NPINDataWebservicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NPINDataWebservicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NPINDataWebservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexResponse GetHIVDataByIndex(Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexRequest request) {
            return base.Channel.GetHIVDataByIndex(request);
        }
        
        public System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexResponse> GetHIVDataByIndexAsync(Cfrva.Sti.Sms.CDCServices.GetHIVDataByIndexRequest request) {
            return base.Channel.GetHIVDataByIndexAsync(request);
        }
        
        public Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateResponse GetHIVDataByState(Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateRequest request) {
            return base.Channel.GetHIVDataByState(request);
        }
        
        public System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateResponse> GetHIVDataByStateAsync(Cfrva.Sti.Sms.CDCServices.GetHIVDataByStateRequest request) {
            return base.Channel.GetHIVDataByStateAsync(request);
        }
        
        public Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexResponse GetSTDDataByIndex(Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexRequest request) {
            return base.Channel.GetSTDDataByIndex(request);
        }
        
        public System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexResponse> GetSTDDataByIndexAsync(Cfrva.Sti.Sms.CDCServices.GetSTDDataByIndexRequest request) {
            return base.Channel.GetSTDDataByIndexAsync(request);
        }
        
        public Cfrva.Sti.Sms.CDCServices.GetWidgetDataResponse GetWidgetData(Cfrva.Sti.Sms.CDCServices.GetWidgetDataRequest request) {
            return base.Channel.GetWidgetData(request);
        }
        
        public System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetWidgetDataResponse> GetWidgetDataAsync(Cfrva.Sti.Sms.CDCServices.GetWidgetDataRequest request) {
            return base.Channel.GetWidgetDataAsync(request);
        }
        
        public Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataResponse GetSTDWidgetData(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataRequest request) {
            return base.Channel.GetSTDWidgetData(request);
        }
        
        public System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataResponse> GetSTDWidgetDataAsync(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataRequest request) {
            return base.Channel.GetSTDWidgetDataAsync(request);
        }
        
        public Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceResponse GetSTDWidgetDataWithAudience(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceRequest request) {
            return base.Channel.GetSTDWidgetDataWithAudience(request);
        }
        
        public System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceResponse> GetSTDWidgetDataWithAudienceAsync(Cfrva.Sti.Sms.CDCServices.GetSTDWidgetDataWithAudienceRequest request) {
            return base.Channel.GetSTDWidgetDataWithAudienceAsync(request);
        }
        
        public Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceResponse GetWidgetDataWithAudience(Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceRequest request) {
            return base.Channel.GetWidgetDataWithAudience(request);
        }
        
        public System.Threading.Tasks.Task<Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceResponse> GetWidgetDataWithAudienceAsync(Cfrva.Sti.Sms.CDCServices.GetWidgetDataWithAudienceRequest request) {
            return base.Channel.GetWidgetDataWithAudienceAsync(request);
        }
    }
}
